version: "3"

services:
  mongo-goerli:
    image: mongo:latest
    container_name: mongo-goerli
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd

  adventurers_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
      - mongo-goerli
    restart: always
    command:
      - run
      - --allow-env=/data/env-goerli
      - /data/src/adventurers.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: adventurers
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

  items_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
      - mongo-goerli
    restart: always
    command:
      - run
      - --allow-env=/data/env-goerli
      - /data/src/items.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: items
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

volumes:
  etcd_data:
  mongo_data: